version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    versioning-strategy: increase-if-necessary
    groups:
      minor-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
      major-dependencies:
        patterns:
          - '*'
        update-types:
          - 'major'
